# Generated by Django 2.0.5 on 2018-06-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworkLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название сети')),
                ('link', models.CharField(max_length=80, verbose_name='Ссылка')),
                ('iconclass', models.CharField(max_length=16, verbose_name='Класс иконки')),
                ('hrefclass', models.CharField(max_length=15, verbose_name='Класс ссылки')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Порядковый номер')),
                ('enabled', models.BooleanField(verbose_name='Включено')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'ordering': ['order'],
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
