# Generated by Django 2.0.5 on 2018-07-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='validators',
            field=models.TextField(blank=True, help_text='Функции проверки видимости меню, например ["validators.is_authenticated"]', verbose_name='Видимость меню'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='hrefclass',
            field=models.CharField(blank=True, help_text='CSS rласс ссылки, обрамляющей URL', max_length=15, verbose_name='Класс ссылки'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='iconclass',
            field=models.CharField(blank=True, help_text='CSS rласс иконки, оформляющей пункт меню, например icon-facebook', max_length=16, verbose_name='Класс иконки'),
        ),
    ]
